---
kind: "operation"
client: "com.atomist:rug"
version: "1.0.0-20170518094744"
generator:
  name: "JavaLibSeed"
  group: "atomist"
  artifact: "spring-team-handlers"
  version: "0.1.117"
  origin:
    repo: "https://www.github.com/atomisthq/spring-team-handlers"
    branch: "master"
    sha: "b1b35af"
  parameters:
    - "org": "spring-team"
    - "repo": "java-lib-seed"
    - "branch": "master"
    - "artifactId": "demo-lib"
    - "groupId": "com.atomist"
    - "version": "0.1.0"
    - "rootPackage": "com.atomist"

---
kind: "operation"
client: "com.atomist:rug"
version: "1.0.0-20170518094744"
editor:
  name: "PrepareTravisBuildFiles"
  group: "atomist"
  artifact: "spring-team-handlers"
  version: "0.1.119"
  origin:
    repo: "git@github.com:atomisthq/spring-team-handlers.git"
    branch: "master"
    sha: "36164c2"
  parameters:
    - "project": "demo-lib"
    - "encryptedGithubToken": "T**********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************="
    - "encryptedArtifactoryUser": "M**********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************="
    - "encryptedArtifactoryToken": "i**********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************="

---
kind: "operation"
client: "com.atomist:rug"
version: "1.0.0-20170518094744"
editor:
  name: "SetArtifactVersionEditor"
  group: "atomist"
  artifact: "spring-team-handlers"
  version: "0.1.122"
  parameters:
    - "desiredVersion": "0.1.1"

---
kind: "operation"
client: "com.atomist:rug"
version: "1.0.0-20170518094744"
editor:
  name: "SetArtifactVersionEditor"
  group: "atomist"
  artifact: "spring-team-handlers"
  version: "0.1.125"
  parameters:
    - "desiredVersion": "0.1.2"

