sudo: required
language: java
install: true
script: bash travis-build.sh
jdk:
- oraclejdk8
env:
  global:
  - secure: Tc6YUjUhLHZh93wevIjJbE6lNdQJdXwKbPKuTUO6TAk8vW/YbJe0bwMlNT4BvtjkWurjSr0Z/GkCxH2boH4nc/ZECViPoG6fY/4T/y5uHUWFTwTaZ9FBT3P1tgG3fTKehhXv+Xno2QCUEbTGbNkzEWxJnCS5cimOw1wbsrkTCrTNu+wZyO5shBHY2wDvXeRLsFWx+6w9CyvBWLZ7xxul2eIREY08w19gNgpQKysarC06wZlcxu+otOSBybIRw1aWjbEZAc15u52gm5QPD1EkCZXtbktZqdUi8W0D3JfzdCT2eujluh1l/1D5BVpO1wkYWGI1JAS1w0EcGYA2PFPbg9zlxJVCgCQa1//g3OiSMFzNm/23/aDJ0H1UjoBqEmEJ+62JRQqG/xkGtElwzuJvz2cRxy9qJ6X2WTe4H40WM4sue4YddIx/OndTK28HL0QmRkkcXgUAZViwzdsixMyOin6dQqXZCB5n6IMyTgUtD16RH4ivpp/f1nhqKSaVgiTtysl1LTfWzdWSeQ43JDvzsUJvTkDBKqiigOdn21R6Lc/U7ygkcBppBlTAV0tHi2Ii8OkTEly2Uh89q+s0jdh35gmUDcwkGMu853b6hF7eemIaLbjGYr2CkPVKzxEuDT8k6VAIwJ3Pp8vApsYlrocDmolfq5R2TNwqyToh0dJowbY=
  - secure: IeDlba8uarCh0CMheHwRyMzhwVZM9ZU4kkfyuE6JgdD98cl6aZylmfqR7tBi8vYEH38XDdOhpTSuFZuTu6P8Nd70TSRLejaG1LhiTkeGz+rnkVrxZdil7elWc1aDeFWIra9NWhz5CD+bEMCncjNfXxIPY8lQFiuh4ZMqkoLsXwJe36ZnksHa9a8YhPzDg2s8/8W1JFAXun7QbjanOtH2gFe4jesU2zzAp/117OyeEXs7Nn7c9kHba9QiLc9ipUKRNDU9aNk8pEhkFqMCXDTlisPaUGuCrg2HedTB1DLO3zPVVOXBLlKcO87wH/vcg9wQiR6KoxYnE1jsPWKBRtYRMmeOYwCTRPSlkfBDNQ3UNXwULJwElTE/RgcdsBRMvK4KBnHcN/E4DavqJ+EkeXB558bfL6OjC+8b4zce4Lyug+IwdBjFyjR6I5XEsQwn3N9JDseSoMX0wzcabQqGgb+xuFJYirFAdrNLAvPOtDA1TYFMqKwE6x4urpECmcUmm6DQaFI2jBSr4rWVgaxpIlqZggmY4zGtkW4s0wsBdzpirKIzoayWMkM1qgnuhEhrRHcLExGs6OlEt5Q2HdKfKqFdDcKs1AaJudNAUhkBrmZJvuhlHDoKzG4Sg8BaIoubKrSxjgdrbFoT2G22m8uYK6qjPamHfIqS1LuMQF3sSm7MXVg=
  - secure: WtkZpCydlJWS1zmOs+0U/Hl7TdAWPwk6DnzZfyv8S9hcghmthS7SOlbg0R1wvg0Tuup0fdXlZXJx7lWRhI86EKMAd15DnsDOzL1l6dk1aslCv7+Ui8GiQ12P+MdJiZNVvH1jpWK6oa46zGN/xLfA1bBYkDFx9LPSdMhekkStEpygyHVV7yPF2IdYNJZ8tBr6SyyFfU0mWBlnP//bnR9EUg3C0cGbATJk75775zOuKjPYdOBVMk9oBJIme/z8nIYFs4QkeOtPCIJ/1uFG8RGmkzB6WDAk/5zE1gR2UYW9AfaKjOYx+4p0YKqy/t99e8N9SehhhPntOV1ArxPKCXm2X+P5MbD3DFhTthsQDs1qCycEVdcxwZAm9nVCFYNX8Vapo5EqB/8M72JaYuM6ZVa5uMBGXN030QJ2e0TIhV2PLHk0zvxQ7HEVnDZFZ3mw/aydfiv3RZC3xi22Q8LgwhkqVyaQolGpH45AsDyQQHsLvGYidtZUNfhDM0CEHdh/zluBNTJYvhCMXP5HnX0c6hGrRPiCXdXIXrp6+kA6O96vVhzJIrvaCgLMMvlUX/JhU4j3vg8l/VeHn+lU7DxZKUtiXFdEf8Dr3xoCBH90ZIUTq2ZIIVUv2IgFFT/2fPzdP/QrW0lGBMAhPUntaJG0RPRjxWiK6CiwYM5UHOoeAmpe6pU=
notifications:
  email: false
  webhooks:
    on_success: always
    on_failure: always
    on_start: always
    on_error: always
    on_cancel: always
    urls:
    - https://webhook.atomist.com/travis
services:
- docker
cache:
  directories:
  - $HOME/.m2
branches:
  except:
  - /^v?\d+\.\d+\.\d+/
